Fix build error for NumPy test package in autopkgtest.
The include path was fixed following this advice. [1] The switch to setuptools
was prompted by PEP 632. [2] We also adopted the fix for the API deprecation
warning suggested in the messages below.

[1] https://stackoverflow.com/a/14657667
[2] https://www.python.org/dev/peps/pep-0632/

Avoids the following build error when building the NumPy test package for
autopkgtest.

Failed build tasks:

>>> t/recipes/../../autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi:
make --trace -f /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/Makefile DEFAULT_DH_COMPAT=13 failed at private/runtests line 787.
Building in /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi
/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/Makefile:63: target 'binaries-missing-depends-on-numpy-abi_1.0.orig.tar.gz' does not exist
mkdir binaries-missing-depends-on-numpy-abi-1.0
if [ -d /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/orig/. ] ; then \
cp -rp /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/orig/. binaries-missing-depends-on-numpy-abi-1.0 ; \
fi
/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/Makefile:35: update target 'binaries-missing-depends-on-numpy-abi_1.0_amd64.changes' due to: binaries-missing-depends-on-numpy-abi_1.0.orig.tar.gz
if [ -r binaries-missing-depends-on-numpy-abi_1.0.orig.tar.gz -a -r /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/upstream/private-key.asc ] ; then \
tmpdir=/tmp/tmp.vcunDdx116 ; \
gpg --homedir "$tmpdir" --import /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/upstream/private-key.asc ; \
gpg --homedir "$tmpdir" --batch --yes --armor --output binaries-missing-depends-on-numpy-abi_1.0.orig.tar.gz.asc \
--detach-sign binaries-missing-depends-on-numpy-abi_1.0.orig.tar.gz ; \
gpg-connect-agent --homedir "$tmpdir" KILLAGENT /bye ; \
rm -rf "$tmpdir" ; \
fi
if [ -d /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/diff/. ] ; then \
cp -rp /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/diff/. binaries-missing-depends-on-numpy-abi-1.0 ; \
fi
if [ -d /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/debian/. ] ; then \
cp -rp /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/debian/. binaries-missing-depends-on-numpy-abi-1.0/debian ; \
fi
if [ -x /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/pre-build ] ; then \
/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/pre-build /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0 ; \
fi
cd binaries-missing-depends-on-numpy-abi-1.0 && dpkg-buildpackage -rfakeroot  -us -uc -d \
-iNEVER_MATCH_ANYTHING -INEVER_MATCH_ANYTHING --source-option=--auto-commit
dpkg-buildpackage: info: source package binaries-missing-depends-on-numpy-abi
dpkg-buildpackage: info: source version 1.0
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Debian Lintian Maintainers <lintian-maint@debian.org>
dpkg-buildpackage: warning: debian/rules is not executable; fixing that
 dpkg-source -iNEVER_MATCH_ANYTHING -INEVER_MATCH_ANYTHING --auto-commit --before-build .
dpkg-buildpackage: info: host architecture amd64
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
 debian/rules clean
make[1]: Entering directory '/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0'
debian/rules:7: target 'clean' does not exist
dh clean --buildsystem pybuild
   dh_auto_clean -O--buildsystem=pybuild
I: pybuild base:237: python3.10 setup.py clean
/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0/setup.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.core
running clean
removing '/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0/.pybuild/cpython3_3.10/build' (and everything under it)
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.10' does not exist -- can't clean it
I: pybuild base:237: python3.9 setup.py clean
running clean
removing '/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0/.pybuild/cpython3_3.9/build' (and everything under it)
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.9' does not exist -- can't clean it
   dh_autoreconf_clean -O--buildsystem=pybuild
   dh_clean -O--buildsystem=pybuild
make[1]: Leaving directory '/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0'
 dpkg-source -iNEVER_MATCH_ANYTHING -INEVER_MATCH_ANYTHING --auto-commit -b .
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building binaries-missing-depends-on-numpy-abi in binaries-missing-depends-on-numpy-abi_1.0.tar.xz
dpkg-source: info: building binaries-missing-depends-on-numpy-abi in binaries-missing-depends-on-numpy-abi_1.0.dsc
 debian/rules binary
make[1]: Entering directory '/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0'
debian/rules:7: target 'binary' does not exist
dh binary --buildsystem pybuild
   dh_update_autotools_config -O--buildsystem=pybuild
   dh_autoreconf -O--buildsystem=pybuild
   dh_auto_configure -O--buildsystem=pybuild
I: pybuild base:237: python3.10 setup.py config
/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0/setup.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.core
running config
I: pybuild base:237: python3.9 setup.py config
running config
   dh_auto_build -O--buildsystem=pybuild
I: pybuild base:237: /usr/bin/python3.10 setup.py build
/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0/setup.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.core
running build
running build_ext
building 'basic' extension
creating build
creating build/temp.linux-x86_64-3.10
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -O2 -ffile-prefix-map=/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.10 -c basic.c -o build/temp.linux-x86_64-3.10/basic.o
basic.c:2:10: fatal error: numpy/arrayobject.h: No such file or directory
    2 | #include <numpy/arrayobject.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
E: pybuild pybuild:354: build: plugin distutils failed with: exit code=1: /usr/bin/python3.10 setup.py build
I: pybuild base:237: /usr/bin/python3 setup.py build
running build
running build_ext
building 'basic' extension
creating build/temp.linux-x86_64-3.9
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -O2 -ffile-prefix-map=/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c basic.c -o build/temp.linux-x86_64-3.9/basic.o
In file included from /usr/include/python3.9/numpy/ndarraytypes.h:1822,
                 from /usr/include/python3.9/numpy/ndarrayobject.h:12,
                 from /usr/include/python3.9/numpy/arrayobject.h:4,
                 from basic.c:2:
/usr/include/python3.9/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
basic.c: In function 'do_import_array':
basic.c:17:5: warning: 'return' with a value, in function returning void [-Wreturn-type]
   17 |     import_array();
      |     ^~~~~~~~~~~~
basic.c:15:6: note: declared here
   15 | void do_import_array(void)
      |      ^~~~~~~~~~~~~~~
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -specs=/usr/share/dpkg/no-pie-link.specs -Wl,-z,relro -Wl,-z,now -Wl,--no-as-needed -g -O2 -ffile-prefix-map=/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/basic.o -o /tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0/.pybuild/cpython3_3.9/build/basic.cpython-39-x86_64-linux-gnu.so
dh_auto_build: error: pybuild --build -i python{version} -p "3.10 3.9" returned exit code 13
make[1]: *** [debian/rules:7: binary] Error 25
make[1]: Leaving directory '/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/packages/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/binaries-missing-depends-on-numpy-abi-1.0'
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make: *** [/tmp/autopkgtest-lxc.v4_16rlk/downtmp/autopkgtest_tmp/build-and-evaluate-test-packages/package-sources/checks/binaries/prerequisites/numpy/binaries-missing-depends-on-numpy-abi/Makefile:39: binaries-missing-depends-on-numpy-abi_1.0_amd64.changes] Error 2

Gbp-Dch: ignore