Restore working directory before attempting to clean up temporary files.
Sometimes a failing check can abort while it is stuck in a temporary
location. That can prevent removal of those files.

After this change, the command below completes without error.

Processing those input files:
    - main/g/glibc/glibc_2.31-12.dsc
    - main/g/glibc/glibc-doc_2.31-12_all.deb
    - main/g/glibc/glibc-source_2.31-12_all.deb
    - main/g/glibc/libc6_2.31-12_amd64.deb
    - main/g/glibc/libc6-dbg_2.31-12_amd64.deb
    - main/g/glibc/libc6-dev_2.31-12_amd64.deb
    - main/g/glibc/libc6-dev-i386_2.31-12_amd64.deb
    - main/g/glibc/libc6-dev-x32_2.31-12_amd64.deb
    - main/g/glibc/libc6-i386_2.31-12_amd64.deb
    - main/g/glibc/libc6-x32_2.31-12_amd64.deb
    - main/g/glibc/libc-bin_2.31-12_amd64.deb
    - main/g/glibc/libc-dev-bin_2.31-12_amd64.deb
    - main/g/glibc/libc-devtools_2.31-12_amd64.deb
    - main/g/glibc/libc-l10n_2.31-12_all.deb
    - main/g/glibc/locales_2.31-12_all.deb
    - main/g/glibc/locales-all_2.31-12_amd64.deb
    - main/g/glibc/nscd_2.31-12_amd64.deb
Running /tmp/Lintian-7PzPe9Ts/Lintian/bin/lintian --display-info --display-experimental --pedantic --display-level +classification --show-overrides --exp-output format=json main/g/glibc/glibc_2.31-12.dsc main/g/glibc/glibc-doc_2.31-12_all.deb main/g/glibc/glibc-source_2.31-12_all.deb main/g/glibc/libc6_2.31-12_amd64.deb main/g/glibc/libc6-dbg_2.31-12_amd64.deb main/g/glibc/libc6-dev_2.31-12_amd64.deb main/g/glibc/libc6-dev-i386_2.31-12_amd64.deb main/g/glibc/libc6-dev-x32_2.31-12_amd64.deb main/g/glibc/libc6-i386_2.31-12_amd64.deb main/g/glibc/libc6-x32_2.31-12_amd64.deb main/g/glibc/libc-bin_2.31-12_amd64.deb main/g/glibc/libc-dev-bin_2.31-12_amd64.deb main/g/glibc/libc-devtools_2.31-12_amd64.deb main/g/glibc/libc-l10n_2.31-12_all.deb main/g/glibc/locales_2.31-12_all.deb main/g/glibc/locales-all_2.31-12_amd64.deb main/g/glibc/nscd_2.31-12_amd64.deb
Lintian terminated with exit status 6400.
ERROR: Warning in group glibc_2.31-12: Output from 'readelf --wide --segments --dynamic --section-details --symbols --version-info usr/lib/debug/.build-id/ec/3a1edbb04c6c2376a0f382429383cb2dfc350e.debug' is not valid UTF-8 at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Index/Objdump.pm line 92.
warning: cannot run debian/control check on package source:glibc_2.31-12
skipping check of source:glibc_2.31-12
Warning in group glibc_2.31-12: Can't call method "get_tag" on an undefined value at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Hint/Bearer.pm line 74.
warning: cannot run group-checks check on package source:glibc_2.31-12
skipping check of source:glibc_2.31-12
Warning in group glibc_2.31-12: Can't call method "get_tag" on an undefined value at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Hint/Bearer.pm line 74.
warning: cannot run documentation/manual check on package binary:libc6-dev_2.31-12_amd64
skipping check of binary:libc6-dev_2.31-12_amd64
Warning in group glibc_2.31-12: Can't call method "get_tag" on an undefined value at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Hint/Bearer.pm line 74.
warning: cannot run menus check on package binary:libc6-dev_2.31-12_amd64
skipping check of binary:libc6-dev_2.31-12_amd64
Warning in group glibc_2.31-12: Can't call method "get_tag" on an undefined value at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Hint/Bearer.pm line 74.
warning: cannot run documentation/manual check on package binary:libc6_2.31-12_amd64
skipping check of binary:libc6_2.31-12_amd64
Warning in group glibc_2.31-12: Can't call method "get_tag" on an undefined value at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Hint/Bearer.pm line 74.
warning: cannot run documentation/manual check on package binary:libc6-dev-x32_2.31-12_amd64
skipping check of binary:libc6-dev-x32_2.31-12_amd64
Warning in group glibc_2.31-12: Can't call method "get_tag" on an undefined value at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Hint/Bearer.pm line 74.
warning: cannot run menus check on package binary:libc6-dev-x32_2.31-12_amd64
skipping check of binary:libc6-dev-x32_2.31-12_amd64
Warning in group glibc_2.31-12: Can't call method "get_tag" on an undefined value at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Hint/Bearer.pm line 74.
warning: cannot run documentation/manual check on package binary:libc6-dev-i386_2.31-12_amd64
skipping check of binary:libc6-dev-i386_2.31-12_amd64
Warning in group glibc_2.31-12: Can't call method "get_tag" on an undefined value at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Hint/Bearer.pm line 74.
warning: cannot run menus check on package binary:libc6-dev-i386_2.31-12_amd64
skipping check of binary:libc6-dev-i386_2.31-12_amd64
remove_tree failed for /tmp/lintian-pool-7byBrfXHtf/glibc/libc6-dbg_2.31-12_amd64_binary: cannot remove path when cwd is /tmp/lintian-pool-7byBrfXHtf/glibc/libc6-dbg_2.31-12_amd64_binary/unpacked at /usr/share/perl5/Path/Tiny.pm line 1732.
        Path::Tiny::remove_tree(Path::Tiny=ARRAY(0x564c315b7d10)) called at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Processable.pm line 237
        Lintian::Processable::remove(Lintian::Processable::Installable=HASH(0x564c205cb948)) called at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Group.pm line 494
        Lintian::Group::clean_lab(Lintian::Group=HASH(0x564c1eec2600), HASH(0x564c20168758)) called at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Group.pm line 469
        Lintian::Group::process(Lintian::Group=HASH(0x564c1eec2600), HASH(0x564c1fb73cc8), HASH(0x564c20168758)) called at /tmp/Lintian-7PzPe9Ts/Lintian/bin/../lib/Lintian/Pool.pm line 169
        Lintian::Pool::process(Lintian::Pool=HASH(0x564c1fb154d8), Lintian::Profile=HASH(0x564c1fec1008), SCALAR(0x564c20180070), HASH(0x564c20168758)) called at /tmp/Lintian-7PzPe9Ts/Lintian/bin/lintian line 706

Gbp-Dch: ignore